/** All Craigslist city subdomains grouped by US state */
export interface CityEntry { subdomain: string; label: string; state: string }

export const CRAIGSLIST_CITIES: CityEntry[] = [
  // Alabama
  { subdomain: "bham", label: "Birmingham", state: "AL" },
  { subdomain: "dothan", label: "Dothan", state: "AL" },
  { subdomain: "shoals", label: "Florence / Muscle Shoals", state: "AL" },
  { subdomain: "gadsden", label: "Gadsden", state: "AL" },
  { subdomain: "huntsv", label: "Huntsville", state: "AL" },
  { subdomain: "mobile", label: "Mobile", state: "AL" },
  { subdomain: "montgomery", label: "Montgomery", state: "AL" },
  { subdomain: "tuscaloosa", label: "Tuscaloosa", state: "AL" },
  // Alaska
  { subdomain: "anchorage", label: "Anchorage", state: "AK" },
  { subdomain: "fairbanks", label: "Fairbanks", state: "AK" },
  { subdomain: "kenai", label: "Kenai Peninsula", state: "AK" },
  { subdomain: "juneau", label: "Juneau", state: "AK" },
  // Arizona
  { subdomain: "flagstaff", label: "Flagstaff", state: "AZ" },
  { subdomain: "mohave", label: "Mohave County", state: "AZ" },
  { subdomain: "phoenix", label: "Phoenix", state: "AZ" },
  { subdomain: "prescott", label: "Prescott", state: "AZ" },
  { subdomain: "showlow", label: "Show Low", state: "AZ" },
  { subdomain: "sierravista", label: "Sierra Vista", state: "AZ" },
  { subdomain: "tucson", label: "Tucson", state: "AZ" },
  { subdomain: "yuma", label: "Yuma", state: "AZ" },
  // Arkansas
  { subdomain: "fayar", label: "Fayetteville", state: "AR" },
  { subdomain: "fortsmith", label: "Fort Smith", state: "AR" },
  { subdomain: "jonesboro", label: "Jonesboro", state: "AR" },
  { subdomain: "littlerock", label: "Little Rock", state: "AR" },
  { subdomain: "texarkana", label: "Texarkana", state: "AR" },
  // California
  { subdomain: "bakersfield", label: "Bakersfield", state: "CA" },
  { subdomain: "chico", label: "Chico", state: "CA" },
  { subdomain: "fresno", label: "Fresno", state: "CA" },
  { subdomain: "goldcountry", label: "Gold Country", state: "CA" },
  { subdomain: "hanford", label: "Hanford", state: "CA" },
  { subdomain: "humboldt", label: "Humboldt County", state: "CA" },
  { subdomain: "imperial", label: "Imperial County", state: "CA" },
  { subdomain: "inlandempire", label: "Inland Empire", state: "CA" },
  { subdomain: "losangeles", label: "Los Angeles", state: "CA" },
  { subdomain: "mendocino", label: "Mendocino County", state: "CA" },
  { subdomain: "merced", label: "Merced", state: "CA" },
  { subdomain: "modesto", label: "Modesto", state: "CA" },
  { subdomain: "monterey", label: "Monterey Bay", state: "CA" },
  { subdomain: "orangecounty", label: "Orange County", state: "CA" },
  { subdomain: "palmsprings", label: "Palm Springs", state: "CA" },
  { subdomain: "redding", label: "Redding", state: "CA" },
  { subdomain: "sacramento", label: "Sacramento", state: "CA" },
  { subdomain: "sandiego", label: "San Diego", state: "CA" },
  { subdomain: "sfbay", label: "San Francisco Bay Area", state: "CA" },
  { subdomain: "slo", label: "San Luis Obispo", state: "CA" },
  { subdomain: "santabarbara", label: "Santa Barbara", state: "CA" },
  { subdomain: "santamaria", label: "Santa Maria", state: "CA" },
  { subdomain: "siskiyou", label: "Siskiyou County", state: "CA" },
  { subdomain: "stockton", label: "Stockton", state: "CA" },
  { subdomain: "susanville", label: "Susanville", state: "CA" },
  { subdomain: "ventura", label: "Ventura County", state: "CA" },
  { subdomain: "visalia", label: "Visalia / Tulare", state: "CA" },
  { subdomain: "yubasutter", label: "Yuba-Sutter", state: "CA" },
  // Colorado
  { subdomain: "boulder", label: "Boulder", state: "CO" },
  { subdomain: "cosprings", label: "Colorado Springs", state: "CO" },
  { subdomain: "denver", label: "Denver", state: "CO" },
  { subdomain: "fortcollins", label: "Fort Collins", state: "CO" },
  { subdomain: "highrockies", label: "High Rockies", state: "CO" },
  { subdomain: "pueblo", label: "Pueblo", state: "CO" },
  { subdomain: "westslope", label: "Western Slope", state: "CO" },
  // Connecticut
  { subdomain: "newhaven", label: "New Haven", state: "CT" },
  { subdomain: "hartford", label: "Hartford", state: "CT" },
  { subdomain: "nwct", label: "Northwest CT", state: "CT" },
  { subdomain: "eastct", label: "Eastern CT", state: "CT" },
  // Delaware
  { subdomain: "delaware", label: "Delaware", state: "DE" },
  // Florida
  { subdomain: "daytona", label: "Daytona Beach", state: "FL" },
  { subdomain: "keys", label: "Florida Keys", state: "FL" },
  { subdomain: "fortlauderdale", label: "Fort Lauderdale", state: "FL" },
  { subdomain: "fortmyers", label: "Fort Myers / SW Florida", state: "FL" },
  { subdomain: "gainesville", label: "Gainesville", state: "FL" },
  { subdomain: "cfl", label: "Heartland Florida", state: "FL" },
  { subdomain: "jacksonville", label: "Jacksonville", state: "FL" },
  { subdomain: "lakeland", label: "Lakeland", state: "FL" },
  { subdomain: "miami", label: "Miami / Dade", state: "FL" },
  { subdomain: "lakecity", label: "North Central FL", state: "FL" },
  { subdomain: "ocala", label: "Ocala", state: "FL" },
  { subdomain: "okaloosa", label: "Okaloosa / Walton", state: "FL" },
  { subdomain: "orlando", label: "Orlando", state: "FL" },
  { subdomain: "panama", label: "Panama City", state: "FL" },
  { subdomain: "pensacola", label: "Pensacola", state: "FL" },
  { subdomain: "sarasota", label: "Sarasota", state: "FL" },
  { subdomain: "spacecoast", label: "Space Coast", state: "FL" },
  { subdomain: "staugustine", label: "St. Augustine", state: "FL" },
  { subdomain: "tallahassee", label: "Tallahassee", state: "FL" },
  { subdomain: "tampa", label: "Tampa Bay", state: "FL" },
  { subdomain: "treasure", label: "Treasure Coast", state: "FL" },
  { subdomain: "miami", label: "West Palm Beach", state: "FL" },
  // Georgia
  { subdomain: "albanyga", label: "Albany", state: "GA" },
  { subdomain: "athens", label: "Athens", state: "GA" },
  { subdomain: "atlanta", label: "Atlanta", state: "GA" },
  { subdomain: "augusta", label: "Augusta", state: "GA" },
  { subdomain: "brunswick", label: "Brunswick", state: "GA" },
  { subdomain: "columbusga", label: "Columbus", state: "GA" },
  { subdomain: "macon", label: "Macon", state: "GA" },
  { subdomain: "nwga", label: "Northwest GA", state: "GA" },
  { subdomain: "savannah", label: "Savannah", state: "GA" },
  { subdomain: "statesboro", label: "Statesboro", state: "GA" },
  { subdomain: "valdosta", label: "Valdosta", state: "GA" },
  // Hawaii
  { subdomain: "honolulu", label: "Honolulu", state: "HI" },
  // Idaho
  { subdomain: "boise", label: "Boise", state: "ID" },
  { subdomain: "eastidaho", label: "East Idaho", state: "ID" },
  { subdomain: "lewiston", label: "Lewiston", state: "ID" },
  { subdomain: "twinfalls", label: "Twin Falls", state: "ID" },
  // Illinois
  { subdomain: "bn", label: "Bloomington-Normal", state: "IL" },
  { subdomain: "chambana", label: "Champaign-Urbana", state: "IL" },
  { subdomain: "chicago", label: "Chicago", state: "IL" },
  { subdomain: "decatur", label: "Decatur", state: "IL" },
  { subdomain: "lasalle", label: "LaSalle County", state: "IL" },
  { subdomain: "mattoon", label: "Mattoon-Charleston", state: "IL" },
  { subdomain: "peoria", label: "Peoria", state: "IL" },
  { subdomain: "rockford", label: "Rockford", state: "IL" },
  { subdomain: "carbondale", label: "Southern Illinois", state: "IL" },
  { subdomain: "springfieldil", label: "Springfield", state: "IL" },
  { subdomain: "quincy", label: "Western Illinois", state: "IL" },
  // Indiana
  { subdomain: "bloomington", label: "Bloomington", state: "IN" },
  { subdomain: "evansville", label: "Evansville", state: "IN" },
  { subdomain: "fortwayne", label: "Fort Wayne", state: "IN" },
  { subdomain: "indianapolis", label: "Indianapolis", state: "IN" },
  { subdomain: "kokomo", label: "Kokomo", state: "IN" },
  { subdomain: "lafayette", label: "Lafayette", state: "IN" },
  { subdomain: "muncie", label: "Muncie / Anderson", state: "IN" },
  { subdomain: "richmondin", label: "Richmond", state: "IN" },
  { subdomain: "southbend", label: "South Bend", state: "IN" },
  { subdomain: "terrehaute", label: "Terre Haute", state: "IN" },
  // Iowa
  { subdomain: "ames", label: "Ames", state: "IA" },
  { subdomain: "cedarrapids", label: "Cedar Rapids", state: "IA" },
  { subdomain: "desmoines", label: "Des Moines", state: "IA" },
  { subdomain: "dubuque", label: "Dubuque", state: "IA" },
  { subdomain: "fortdodge", label: "Fort Dodge", state: "IA" },
  { subdomain: "iowacity", label: "Iowa City", state: "IA" },
  { subdomain: "masoncity", label: "Mason City", state: "IA" },
  { subdomain: "quadcities", label: "Quad Cities", state: "IA" },
  { subdomain: "siouxcity", label: "Sioux City", state: "IA" },
  { subdomain: "ottumwa", label: "Southeast Iowa", state: "IA" },
  { subdomain: "waterloo", label: "Waterloo", state: "IA" },
  // Kansas
  { subdomain: "lawrence", label: "Lawrence", state: "KS" },
  { subdomain: "ksu", label: "Manhattan", state: "KS" },
  { subdomain: "nwks", label: "Northwest Kansas", state: "KS" },
  { subdomain: "salina", label: "Salina", state: "KS" },
  { subdomain: "seks", label: "Southeast Kansas", state: "KS" },
  { subdomain: "swks", label: "Southwest Kansas", state: "KS" },
  { subdomain: "topeka", label: "Topeka", state: "KS" },
  { subdomain: "wichita", label: "Wichita", state: "KS" },
  // Kentucky
  { subdomain: "bgky", label: "Bowling Green", state: "KY" },
  { subdomain: "eastky", label: "Eastern Kentucky", state: "KY" },
  { subdomain: "lexington", label: "Lexington", state: "KY" },
  { subdomain: "louisville", label: "Louisville", state: "KY" },
  { subdomain: "owensboro", label: "Owensboro", state: "KY" },
  { subdomain: "westky", label: "Western Kentucky", state: "KY" },
  // Louisiana
  { subdomain: "batonrouge", label: "Baton Rouge", state: "LA" },
  { subdomain: "cenla", label: "Central Louisiana", state: "LA" },
  { subdomain: "houma", label: "Houma", state: "LA" },
  { subdomain: "lafayette", label: "Lafayette", state: "LA" },
  { subdomain: "lakecharles", label: "Lake Charles", state: "LA" },
  { subdomain: "monroe", label: "Monroe", state: "LA" },
  { subdomain: "neworleans", label: "New Orleans", state: "LA" },
  { subdomain: "shreveport", label: "Shreveport", state: "LA" },
  // Maine
  { subdomain: "maine", label: "Maine", state: "ME" },
  // Maryland
  { subdomain: "annapolis", label: "Annapolis", state: "MD" },
  { subdomain: "baltimore", label: "Baltimore", state: "MD" },
  { subdomain: "easternshore", label: "Eastern Shore", state: "MD" },
  { subdomain: "frederick", label: "Frederick", state: "MD" },
  { subdomain: "smd", label: "Southern Maryland", state: "MD" },
  { subdomain: "westmd", label: "Western Maryland", state: "MD" },
  // Massachusetts
  { subdomain: "boston", label: "Boston", state: "MA" },
  { subdomain: "capecod", label: "Cape Cod", state: "MA" },
  { subdomain: "southcoast", label: "South Coast", state: "MA" },
  { subdomain: "westernmass", label: "Western Mass", state: "MA" },
  { subdomain: "worcester", label: "Worcester", state: "MA" },
  // Michigan
  { subdomain: "annarbor", label: "Ann Arbor", state: "MI" },
  { subdomain: "battlecreek", label: "Battle Creek", state: "MI" },
  { subdomain: "centralmich", label: "Central Michigan", state: "MI" },
  { subdomain: "detroit", label: "Detroit Metro", state: "MI" },
  { subdomain: "flint", label: "Flint", state: "MI" },
  { subdomain: "grandrapids", label: "Grand Rapids", state: "MI" },
  { subdomain: "holland", label: "Holland", state: "MI" },
  { subdomain: "jxn", label: "Jackson", state: "MI" },
  { subdomain: "kalamazoo", label: "Kalamazoo", state: "MI" },
  { subdomain: "lansing", label: "Lansing", state: "MI" },
  { subdomain: "monroemi", label: "Monroe", state: "MI" },
  { subdomain: "muskegon", label: "Muskegon", state: "MI" },
  { subdomain: "nmi", label: "Northern Michigan", state: "MI" },
  { subdomain: "porthuron", label: "Port Huron", state: "MI" },
  { subdomain: "saginaw", label: "Saginaw", state: "MI" },
  { subdomain: "swmi", label: "Southwest Michigan", state: "MI" },
  { subdomain: "thumb", label: "The Thumb", state: "MI" },
  { subdomain: "up", label: "Upper Peninsula", state: "MI" },
  // Minnesota
  { subdomain: "bemidji", label: "Bemidji", state: "MN" },
  { subdomain: "brainerd", label: "Brainerd", state: "MN" },
  { subdomain: "duluth", label: "Duluth / Superior", state: "MN" },
  { subdomain: "mankato", label: "Mankato", state: "MN" },
  { subdomain: "minneapolis", label: "Minneapolis / St. Paul", state: "MN" },
  { subdomain: "rmn", label: "Rochester", state: "MN" },
  { subdomain: "marshall", label: "Southwest MN", state: "MN" },
  { subdomain: "stcloud", label: "St. Cloud", state: "MN" },
  // Mississippi
  { subdomain: "gulfport", label: "Gulfport / Biloxi", state: "MS" },
  { subdomain: "hattiesburg", label: "Hattiesburg", state: "MS" },
  { subdomain: "jackson", label: "Jackson", state: "MS" },
  { subdomain: "meridian", label: "Meridian", state: "MS" },
  { subdomain: "northmiss", label: "North Mississippi", state: "MS" },
  { subdomain: "natchez", label: "Southwest MS", state: "MS" },
  // Missouri
  { subdomain: "columbiamo", label: "Columbia / Jeff City", state: "MO" },
  { subdomain: "joplin", label: "Joplin", state: "MO" },
  { subdomain: "kansascity", label: "Kansas City", state: "MO" },
  { subdomain: "kirksville", label: "Kirksville", state: "MO" },
  { subdomain: "loz", label: "Lake of the Ozarks", state: "MO" },
  { subdomain: "semo", label: "Southeast Missouri", state: "MO" },
  { subdomain: "springfield", label: "Springfield", state: "MO" },
  { subdomain: "stjoseph", label: "St. Joseph", state: "MO" },
  { subdomain: "stlouis", label: "St. Louis", state: "MO" },
  // Montana
  { subdomain: "billings", label: "Billings", state: "MT" },
  { subdomain: "bozeman", label: "Bozeman", state: "MT" },
  { subdomain: "butte", label: "Butte", state: "MT" },
  { subdomain: "greatfalls", label: "Great Falls", state: "MT" },
  { subdomain: "helena", label: "Helena", state: "MT" },
  { subdomain: "kalispell", label: "Kalispell", state: "MT" },
  { subdomain: "missoula", label: "Missoula", state: "MT" },
  { subdomain: "montana", label: "Eastern Montana", state: "MT" },
  // Nebraska
  { subdomain: "grandisland", label: "Grand Island", state: "NE" },
  { subdomain: "lincoln", label: "Lincoln", state: "NE" },
  { subdomain: "northplatte", label: "North Platte", state: "NE" },
  { subdomain: "omaha", label: "Omaha", state: "NE" },
  { subdomain: "scottsbluff", label: "Scottsbluff / Panhandle", state: "NE" },
  // Nevada
  { subdomain: "elko", label: "Elko", state: "NV" },
  { subdomain: "lasvegas", label: "Las Vegas", state: "NV" },
  { subdomain: "reno", label: "Reno / Tahoe", state: "NV" },
  // New Hampshire
  { subdomain: "nh", label: "New Hampshire", state: "NH" },
  // New Jersey
  { subdomain: "cnj", label: "Central NJ", state: "NJ" },
  { subdomain: "jerseyshore", label: "Jersey Shore", state: "NJ" },
  { subdomain: "newjersey", label: "North Jersey", state: "NJ" },
  { subdomain: "southjersey", label: "South Jersey", state: "NJ" },
  // New Mexico
  { subdomain: "albuquerque", label: "Albuquerque", state: "NM" },
  { subdomain: "clovis", label: "Clovis / Portales", state: "NM" },
  { subdomain: "farmington", label: "Farmington", state: "NM" },
  { subdomain: "lascruces", label: "Las Cruces", state: "NM" },
  { subdomain: "roswell", label: "Roswell / Carlsbad", state: "NM" },
  { subdomain: "santafe", label: "Santa Fe", state: "NM" },
  // New York
  { subdomain: "albany", label: "Albany", state: "NY" },
  { subdomain: "binghamton", label: "Binghamton", state: "NY" },
  { subdomain: "buffalo", label: "Buffalo", state: "NY" },
  { subdomain: "catskills", label: "Catskills", state: "NY" },
  { subdomain: "chautauqua", label: "Chautauqua", state: "NY" },
  { subdomain: "elmira", label: "Elmira / Corning", state: "NY" },
  { subdomain: "fingerlakes", label: "Finger Lakes", state: "NY" },
  { subdomain: "glensfalls", label: "Glens Falls", state: "NY" },
  { subdomain: "hudsonvalley", label: "Hudson Valley", state: "NY" },
  { subdomain: "ithaca", label: "Ithaca", state: "NY" },
  { subdomain: "longisland", label: "Long Island", state: "NY" },
  { subdomain: "newyork", label: "New York City", state: "NY" },
  { subdomain: "oneonta", label: "Oneonta", state: "NY" },
  { subdomain: "plattsburgh", label: "Plattsburgh", state: "NY" },
  { subdomain: "potsdam", label: "Potsdam-Canton", state: "NY" },
  { subdomain: "rochester", label: "Rochester", state: "NY" },
  { subdomain: "syracuse", label: "Syracuse", state: "NY" },
  { subdomain: "utica", label: "Utica-Rome", state: "NY" },
  { subdomain: "watertown", label: "Watertown", state: "NY" },
  // North Carolina
  { subdomain: "asheville", label: "Asheville", state: "NC" },
  { subdomain: "boone", label: "Boone", state: "NC" },
  { subdomain: "charlotte", label: "Charlotte", state: "NC" },
  { subdomain: "eastnc", label: "Eastern NC", state: "NC" },
  { subdomain: "fayetteville", label: "Fayetteville", state: "NC" },
  { subdomain: "greensboro", label: "Greensboro", state: "NC" },
  { subdomain: "hickory", label: "Hickory / Lenoir", state: "NC" },
  { subdomain: "outerbanks", label: "Outer Banks", state: "NC" },
  { subdomain: "raleigh", label: "Raleigh / Durham", state: "NC" },
  { subdomain: "wilmington", label: "Wilmington", state: "NC" },
  { subdomain: "winstonsalem", label: "Winston-Salem", state: "NC" },
  // North Dakota
  { subdomain: "bismarck", label: "Bismarck", state: "ND" },
  { subdomain: "fargo", label: "Fargo / Moorhead", state: "ND" },
  { subdomain: "grandforks", label: "Grand Forks", state: "ND" },
  { subdomain: "nd", label: "North Dakota", state: "ND" },
  // Ohio
  { subdomain: "akroncanton", label: "Akron / Canton", state: "OH" },
  { subdomain: "ashtabula", label: "Ashtabula", state: "OH" },
  { subdomain: "chillicothe", label: "Chillicothe", state: "OH" },
  { subdomain: "cincinnati", label: "Cincinnati", state: "OH" },
  { subdomain: "cleveland", label: "Cleveland", state: "OH" },
  { subdomain: "columbus", label: "Columbus", state: "OH" },
  { subdomain: "dayton", label: "Dayton / Springfield", state: "OH" },
  { subdomain: "limaohio", label: "Lima / Findlay", state: "OH" },
  { subdomain: "mansfield", label: "Mansfield", state: "OH" },
  { subdomain: "sandusky", label: "Sandusky", state: "OH" },
  { subdomain: "toledo", label: "Toledo", state: "OH" },
  { subdomain: "tuscarawas", label: "Tuscarawas County", state: "OH" },
  { subdomain: "youngstown", label: "Youngstown", state: "OH" },
  { subdomain: "zanesville", label: "Zanesville / Cambridge", state: "OH" },
  // Oklahoma
  { subdomain: "lawton", label: "Lawton", state: "OK" },
  { subdomain: "enid", label: "Northwest OK", state: "OK" },
  { subdomain: "oklahomacity", label: "Oklahoma City", state: "OK" },
  { subdomain: "stillwater", label: "Stillwater", state: "OK" },
  { subdomain: "tulsa", label: "Tulsa", state: "OK" },
  // Oregon
  { subdomain: "bend", label: "Bend", state: "OR" },
  { subdomain: "corvallis", label: "Corvallis / Albany", state: "OR" },
  { subdomain: "eastoregon", label: "East Oregon", state: "OR" },
  { subdomain: "eugene", label: "Eugene", state: "OR" },
  { subdomain: "klamath", label: "Klamath Falls", state: "OR" },
  { subdomain: "medford", label: "Medford-Ashland", state: "OR" },
  { subdomain: "oregoncoast", label: "Oregon Coast", state: "OR" },
  { subdomain: "portland", label: "Portland", state: "OR" },
  { subdomain: "roseburg", label: "Roseburg", state: "OR" },
  { subdomain: "salem", label: "Salem", state: "OR" },
  // Pennsylvania
  { subdomain: "altoona", label: "Altoona-Johnstown", state: "PA" },
  { subdomain: "chambersburg", label: "Cumberland Valley", state: "PA" },
  { subdomain: "erie", label: "Erie", state: "PA" },
  { subdomain: "harrisburg", label: "Harrisburg", state: "PA" },
  { subdomain: "lancaster", label: "Lancaster", state: "PA" },
  { subdomain: "allentown", label: "Lehigh Valley", state: "PA" },
  { subdomain: "meadville", label: "Meadville", state: "PA" },
  { subdomain: "philadelphia", label: "Philadelphia", state: "PA" },
  { subdomain: "pittsburgh", label: "Pittsburgh", state: "PA" },
  { subdomain: "poconos", label: "Poconos", state: "PA" },
  { subdomain: "reading", label: "Reading", state: "PA" },
  { subdomain: "scranton", label: "Scranton / Wilkes-Barre", state: "PA" },
  { subdomain: "pennstate", label: "State College", state: "PA" },
  { subdomain: "williamsport", label: "Williamsport", state: "PA" },
  { subdomain: "york", label: "York", state: "PA" },
  // Rhode Island
  { subdomain: "providence", label: "Providence", state: "RI" },
  // South Carolina
  { subdomain: "charleston", label: "Charleston", state: "SC" },
  { subdomain: "columbia", label: "Columbia", state: "SC" },
  { subdomain: "florencesc", label: "Florence", state: "SC" },
  { subdomain: "greenville", label: "Greenville / Upstate", state: "SC" },
  { subdomain: "hiltonhead", label: "Hilton Head", state: "SC" },
  { subdomain: "myrtlebeach", label: "Myrtle Beach", state: "SC" },
  // South Dakota
  { subdomain: "nesd", label: "Northeast SD", state: "SD" },
  { subdomain: "csd", label: "Pierre / Central SD", state: "SD" },
  { subdomain: "rapidcity", label: "Rapid City", state: "SD" },
  { subdomain: "siouxfalls", label: "Sioux Falls", state: "SD" },
  { subdomain: "sd", label: "South Dakota", state: "SD" },
  // Tennessee
  { subdomain: "chattanooga", label: "Chattanooga", state: "TN" },
  { subdomain: "clarksville", label: "Clarksville", state: "TN" },
  { subdomain: "cookeville", label: "Cookeville", state: "TN" },
  { subdomain: "jacksontn", label: "Jackson", state: "TN" },
  { subdomain: "knoxville", label: "Knoxville", state: "TN" },
  { subdomain: "memphis", label: "Memphis", state: "TN" },
  { subdomain: "nashville", label: "Nashville", state: "TN" },
  { subdomain: "tricities", label: "Tri-Cities", state: "TN" },
  // Texas
  { subdomain: "abilene", label: "Abilene", state: "TX" },
  { subdomain: "amarillo", label: "Amarillo", state: "TX" },
  { subdomain: "austin", label: "Austin", state: "TX" },
  { subdomain: "beaumont", label: "Beaumont / Port Arthur", state: "TX" },
  { subdomain: "brownsville", label: "Brownsville", state: "TX" },
  { subdomain: "collegestation", label: "College Station", state: "TX" },
  { subdomain: "corpuschristi", label: "Corpus Christi", state: "TX" },
  { subdomain: "dallas", label: "Dallas / Fort Worth", state: "TX" },
  { subdomain: "nacogdoches", label: "Deep East Texas", state: "TX" },
  { subdomain: "delrio", label: "Del Rio / Eagle Pass", state: "TX" },
  { subdomain: "elpaso", label: "El Paso", state: "TX" },
  { subdomain: "galveston", label: "Galveston", state: "TX" },
  { subdomain: "houston", label: "Houston", state: "TX" },
  { subdomain: "killeen", label: "Killeen / Temple", state: "TX" },
  { subdomain: "laredo", label: "Laredo", state: "TX" },
  { subdomain: "lubbock", label: "Lubbock", state: "TX" },
  { subdomain: "mcallen", label: "McAllen / Edinburg", state: "TX" },
  { subdomain: "odessa", label: "Odessa / Midland", state: "TX" },
  { subdomain: "sanangelo", label: "San Angelo", state: "TX" },
  { subdomain: "sanantonio", label: "San Antonio", state: "TX" },
  { subdomain: "sanmarcos", label: "San Marcos", state: "TX" },
  { subdomain: "texoma", label: "Texoma", state: "TX" },
  { subdomain: "easttexas", label: "Tyler / East Texas", state: "TX" },
  { subdomain: "victoriatx", label: "Victoria", state: "TX" },
  { subdomain: "waco", label: "Waco", state: "TX" },
  { subdomain: "wichitafalls", label: "Wichita Falls", state: "TX" },
  // Utah
  { subdomain: "logan", label: "Logan", state: "UT" },
  { subdomain: "ogden", label: "Ogden-Clearfield", state: "UT" },
  { subdomain: "provo", label: "Provo / Orem", state: "UT" },
  { subdomain: "saltlakecity", label: "Salt Lake City", state: "UT" },
  { subdomain: "stgeorge", label: "St. George", state: "UT" },
  // Vermont
  { subdomain: "burlington", label: "Burlington", state: "VT" },
  // Virginia
  { subdomain: "charlottesville", label: "Charlottesville", state: "VA" },
  { subdomain: "danville", label: "Danville", state: "VA" },
  { subdomain: "fredericksburg", label: "Fredericksburg", state: "VA" },
  { subdomain: "harrisonburg", label: "Harrisonburg", state: "VA" },
  { subdomain: "lynchburg", label: "Lynchburg", state: "VA" },
  { subdomain: "blacksburg", label: "New River Valley", state: "VA" },
  { subdomain: "norfolk", label: "Norfolk / Hampton Roads", state: "VA" },
  { subdomain: "richmond", label: "Richmond", state: "VA" },
  { subdomain: "roanoke", label: "Roanoke", state: "VA" },
  { subdomain: "swva", label: "Southwest VA", state: "VA" },
  { subdomain: "winchester", label: "Winchester", state: "VA" },
  // Washington DC
  { subdomain: "washingtondc", label: "Washington, DC", state: "DC" },
  // Washington State
  { subdomain: "bellingham", label: "Bellingham", state: "WA" },
  { subdomain: "kpr", label: "Kennewick-Richland", state: "WA" },
  { subdomain: "moseslake", label: "Moses Lake", state: "WA" },
  { subdomain: "olympic", label: "Olympic Peninsula", state: "WA" },
  { subdomain: "pullman", label: "Pullman / Moscow", state: "WA" },
  { subdomain: "seattle", label: "Seattle-Tacoma", state: "WA" },
  { subdomain: "skagit", label: "Skagit / Island", state: "WA" },
  { subdomain: "spokane", label: "Spokane", state: "WA" },
  { subdomain: "wenatchee", label: "Wenatchee", state: "WA" },
  { subdomain: "yakima", label: "Yakima", state: "WA" },
  // West Virginia
  { subdomain: "charlestonwv", label: "Charleston", state: "WV" },
  { subdomain: "martinsburg", label: "Eastern Panhandle", state: "WV" },
  { subdomain: "huntington", label: "Huntington-Ashland", state: "WV" },
  { subdomain: "morgantown", label: "Morgantown", state: "WV" },
  { subdomain: "ohioriver", label: "Northern Panhandle", state: "WV" },
  { subdomain: "parkersburg", label: "Parkersburg-Marietta", state: "WV" },
  { subdomain: "swv", label: "Southern WV", state: "WV" },
  { subdomain: "wv", label: "West Virginia (old)", state: "WV" },
  // Wisconsin
  { subdomain: "appleton", label: "Appleton-Oshkosh", state: "WI" },
  { subdomain: "eauclaire", label: "Eau Claire", state: "WI" },
  { subdomain: "greenbay", label: "Green Bay", state: "WI" },
  { subdomain: "janesville", label: "Janesville", state: "WI" },
  { subdomain: "racine", label: "Kenosha-Racine", state: "WI" },
  { subdomain: "lacrosse", label: "La Crosse", state: "WI" },
  { subdomain: "madison", label: "Madison", state: "WI" },
  { subdomain: "milwaukee", label: "Milwaukee", state: "WI" },
  { subdomain: "northernwi", label: "Northern WI", state: "WI" },
  { subdomain: "sheboygan", label: "Sheboygan", state: "WI" },
  { subdomain: "wausau", label: "Wausau", state: "WI" },
  // Wyoming
  { subdomain: "wyoming", label: "Wyoming", state: "WY" },
];

/** Get unique state codes sorted */
export const STATES = [...new Set(CRAIGSLIST_CITIES.map(c => c.state))].sort();

/** Get cities for a given state */
export const citiesByState = (state: string) =>
  CRAIGSLIST_CITIES.filter(c => c.state === state);
