// Director Camera Styles — Movie Camera Language Engine
// Each entry maps an iconic cinematic style to prompt-injection language for Seedance.

export type DirectorCategory =
  | 'Handheld & Chaotic'
  | 'Smooth Tracking & Steadicam'
  | 'Signature Effects'
  | 'Creative Angles & Framing'
  | 'Viral / Experimental / Time';

export interface DirectorStyle {
  id: string;
  title: string;          // Movie / music video / director title
  shotName: string;       // Camera style name
  category: DirectorCategory;
  description: string;
  motion_behavior: string[];
  emotional_tone: string[];
  cinematic_keywords: string[];
  prompt_injection: string;          // Sentence appended to the user prompt
  lens_language?: string;
  motion_language?: string;
  lighting_language?: string;
  youtube_id?: string;               // YouTube video ID (best-effort)
  start_time: number;                // seconds
  end_time: number;                  // seconds
  thumbnail?: string;                // Falls back to youtube hqdefault
  tags: string[];                    // 'viral', 'cinematic', 'action', 'horror', 'music-video', 'real-estate', 'documentary'
}

const t = (...s: string[]) => s;

export const DIRECTOR_STYLES: DirectorStyle[] = [
  // ───────── HANDHELD & CHAOTIC ─────────
  {
    id: 'cloverfield', title: 'Cloverfield', shotName: 'Found-footage panic handheld',
    category: 'Handheld & Chaotic',
    description: 'Raw found-footage chaos. Panic-driven instability, imperfect framing, emergency realism.',
    motion_behavior: t('aggressive shake','reactive operator','imperfect framing'),
    emotional_tone: t('panic','urgency','dread'),
    cinematic_keywords: t('handheld','found footage','documentary disaster'),
    prompt_injection: 'raw handheld found-footage cinematography, chaotic shaky camera movement, imperfect emergency framing, panic realism, unstable documentary motion blur, reactive operator movement, immersive disaster-film energy',
    lens_language: 'wide consumer camcorder lens, slight barrel distortion, low-light grain',
    motion_language: 'unstable run-and-gun handheld with sudden jerks and re-framing',
    lighting_language: 'available light, blown highlights, harsh practical sources',
    youtube_id: '_afPFLvh2qg', start_time: 18, end_time: 30,
    tags: t('horror','action','viral'),
  },
  {
    id: 'children-of-men', title: 'Children of Men', shotName: 'Immersive one-take war chaos',
    category: 'Handheld & Chaotic',
    description: 'Continuous unbroken handheld through war-zone chaos. Survival realism.',
    motion_behavior: t('continuous take','reactive follow','sustained tension'),
    emotional_tone: t('survival','grief','awe'),
    cinematic_keywords: t('long-take','immersive','wartime'),
    prompt_injection: 'unbroken single-take handheld cinematography, reactive operator following the subject through chaos, grounded survival realism, naturalistic motion, ambient blood-on-lens imperfection, breath-level intimacy',
    lens_language: '24-35mm immersive prime, slight shoulder shake',
    motion_language: 'continuous walking handheld follow, no cuts',
    lighting_language: 'natural overcast, smoke, fire flicker',
    youtube_id: 'YIINChTTyhs', start_time: 30, end_time: 75,
    tags: t('cinematic','action','documentary'),
  },
  {
    id: 'revenant', title: 'The Revenant', shotName: 'Natural-light breathing realism',
    category: 'Handheld & Chaotic',
    description: 'Intimate handheld with natural light, breath visible on lens, immersive survival.',
    motion_behavior: t('breath-driven','close intimate','reactive'),
    emotional_tone: t('survival','spiritual','raw'),
    cinematic_keywords: t('natural light','wide lens intimacy','breath on lens'),
    prompt_injection: 'natural-light handheld cinematography, breath fogging the lens, intimate wide-lens proximity, raw survival realism, magic-hour color, soft kinetic camera drift',
    lens_language: 'Arri Alexa wide primes, very low-light sensitivity',
    motion_language: 'gentle handheld breathing motion, occasional close push-ins',
    lighting_language: 'only natural light, magic hour, firelight, snow bounce',
    youtube_id: '_8P8MgsFNZQ', start_time: 25, end_time: 60,
    tags: t('cinematic','documentary'),
  },
  {
    id: 'blair-witch', title: 'The Blair Witch Project', shotName: 'Unstable horror handheld',
    category: 'Handheld & Chaotic',
    description: 'Pure found-footage horror. Unstable framing, low-fidelity, deeply uncomfortable.',
    motion_behavior: t('uncontrolled shake','low-fi','first-person'),
    emotional_tone: t('terror','disorientation','dread'),
    cinematic_keywords: t('handheld camcorder','low-fi','first-person fear'),
    prompt_injection: 'low-fidelity camcorder handheld footage, uncontrolled shaking, first-person horror perspective, harsh on-camera light, panicked breathing motion, disoriented imperfect framing',
    youtube_id: 'MBZ-POVsrlI', start_time: 90, end_time: 110,
    tags: t('horror','viral'),
  },
  {
    id: 'saving-private-ryan', title: 'Saving Private Ryan', shotName: 'Aggressive war-doc handheld',
    category: 'Handheld & Chaotic',
    description: 'Shutter-stripped 90s combat realism. Concussive, desaturated, urgent.',
    motion_behavior: t('combat shake','concussive impact','reactive duck-and-cover'),
    emotional_tone: t('terror','chaos','heroism'),
    cinematic_keywords: t('45-degree shutter','desaturated','combat handheld'),
    prompt_injection: 'aggressive combat handheld cinematography, 45-degree shutter stutter, desaturated bleach-bypass color, concussive shake on impacts, war-documentary immediacy, reactive duck-and-cover operator',
    youtube_id: 'XijMMhs55oc', start_time: 40, end_time: 90,
    tags: t('action','cinematic'),
  },
  {
    id: 'city-of-god', title: 'City of God', shotName: 'Kinetic street realism',
    category: 'Handheld & Chaotic',
    description: 'Whip-fast handheld through favela streets. Sun-drenched, kinetic energy.',
    motion_behavior: t('whip pans','run-with-subject','snap zooms'),
    emotional_tone: t('vibrant','dangerous','alive'),
    cinematic_keywords: t('snap zoom','sun-bleached','street kinetic'),
    prompt_injection: 'kinetic street handheld cinematography, snap zooms and whip pans, sun-bleached high-contrast color, run-with-subject momentum, vibrant favela energy, gritty urban realism',
    youtube_id: 'dcUOO4Itgmw', start_time: 10, end_time: 60,
    tags: t('action','cinematic','music-video'),
  },
  {
    id: 'big-short', title: 'The Big Short', shotName: 'Documentary-style realism',
    category: 'Handheld & Chaotic',
    description: 'Loose handheld realism with reactive zooms — financial-doc style.',
    motion_behavior: t('reactive zoom','loose handheld','observational'),
    emotional_tone: t('clinical','urgent','wry'),
    cinematic_keywords: t('reactive zoom','observational doc','loose framing'),
    prompt_injection: 'documentary-style loose handheld cinematography, reactive zoom adjustments, observational framing, naturalistic office light, loose realism, casual reframes',
    youtube_id: 'vgqG3ITMv1Q', start_time: 30, end_time: 60,
    tags: t('documentary','cinematic'),
  },
  {
    id: '28-days-later', title: '28 Days Later', shotName: 'Urgent infected chase motion',
    category: 'Handheld & Chaotic',
    description: 'Digital low-res handheld with stuttering frame-rate chase energy.',
    motion_behavior: t('frame-rate stutter','sprint follow','jagged'),
    emotional_tone: t('terror','sprint','dread'),
    cinematic_keywords: t('low-fi DV','frame stutter','infected chase'),
    prompt_injection: 'low-fi digital video handheld, jagged stuttering frame-rate, sprint-follow chase motion, infected-chase urgency, desolate post-apocalyptic palette, raw on-the-shoulder framing',
    youtube_id: 'mWEhfF27O0c', start_time: 30, end_time: 70,
    tags: t('horror','action'),
  },
  {
    id: 'birdman', title: 'Birdman', shotName: 'Pseudo one-shot floating handheld',
    category: 'Handheld & Chaotic',
    description: 'Theatrical Steadicam masquerading as a single continuous take.',
    motion_behavior: t('continuous follow','floating glide','through doorways'),
    emotional_tone: t('theatrical','anxious','propulsive'),
    cinematic_keywords: t('pseudo one-take','theatrical glide','steadicam'),
    prompt_injection: 'continuous one-take floating handheld through theatrical corridors, smooth-but-alive steadicam glide, hidden cut illusion, propulsive percussive pacing, intimate doorway transitions',
    youtube_id: 'uJfLoE6hanc', start_time: 30, end_time: 90,
    tags: t('cinematic'),
  },
  {
    id: 'mad-max', title: 'Mad Max: Fury Road', shotName: 'Center-frame action chaos',
    category: 'Handheld & Chaotic',
    description: 'Hyper-saturated center-punched chaos. Every object reads instantly.',
    motion_behavior: t('center-punched','speed ramps','hyper-clarity'),
    emotional_tone: t('manic','propulsive','operatic'),
    cinematic_keywords: t('center frame','speed ramp','hyper-saturated'),
    prompt_injection: 'center-punched action cinematography with speed ramps, hyper-saturated orange-and-teal color, manic propulsive editing, operatic chaos clarity, kinetic vehicle parallax',
    youtube_id: 'hEJnMQG9ev8', start_time: 60, end_time: 120,
    tags: t('action','cinematic','viral'),
  },

  // ───────── SMOOTH TRACKING & STEADICAM ─────────
  {
    id: 'goodfellas', title: 'Goodfellas', shotName: 'Copacabana tracking elegance',
    category: 'Smooth Tracking & Steadicam',
    description: 'Effortless Steadicam through service halls into the club — power and access.',
    motion_behavior: t('continuous tracking','through tight spaces','character follow'),
    emotional_tone: t('elegant','intimate','aspirational'),
    cinematic_keywords: t('steadicam','single take','luxury entry'),
    prompt_injection: 'elegant continuous steadicam tracking through service corridors into a luxurious main room, character-follow framing, warm tungsten color, effortless gliding motion, sense of access and privilege',
    youtube_id: 'mcXBP-1fduY', start_time: 0, end_time: 180,
    tags: t('cinematic','real-estate','music-video'),
  },
  {
    id: '1917', title: '1917', shotName: 'Continuous immersive tracking',
    category: 'Smooth Tracking & Steadicam',
    description: 'Sustained Steadicam realism that puts you alongside the subject.',
    motion_behavior: t('sustained follow','seamless geography','hidden cuts'),
    emotional_tone: t('immersive','tense','heroic'),
    cinematic_keywords: t('one-take','steadicam','war-zone immersion'),
    prompt_injection: 'continuous immersive steadicam tracking shot, seamless real-time geography, hidden cuts, tense survival pacing, naturalistic light, viewer-walks-alongside intimacy',
    youtube_id: 'gZjQROMAh_s', start_time: 0, end_time: 60,
    tags: t('cinematic','action'),
  },
  {
    id: 'shining', title: 'The Shining', shotName: 'Smooth horror steadicam',
    category: 'Smooth Tracking & Steadicam',
    description: 'Low-mounted Steadicam following at constant distance — unnerving calm.',
    motion_behavior: t('low-mount','constant-distance follow','symmetrical'),
    emotional_tone: t('uncanny','dread','still'),
    cinematic_keywords: t('low steadicam','symmetrical corridor','unnerving calm'),
    prompt_injection: 'low-mounted steadicam following at perfectly constant distance through symmetrical corridors, uncanny calm, dread without movement spikes, hotel carpet rolling under the lens',
    youtube_id: '5Cb3ik6zP2I', start_time: 0, end_time: 30,
    tags: t('horror','cinematic'),
  },
  {
    id: 'russian-ark', title: 'Russian Ark', shotName: 'Uninterrupted museum floating',
    category: 'Smooth Tracking & Steadicam',
    description: 'A single 96-minute take floating through history.',
    motion_behavior: t('continuous float','crowd weaving','room-to-room'),
    emotional_tone: t('reverent','dreamlike','grand'),
    cinematic_keywords: t('continuous take','floating glide','historical halls'),
    prompt_injection: 'continuous uninterrupted floating steadicam through grand palace halls, weaving past crowds, reverent dreamlike grandeur, gilded warm light',
    youtube_id: 'ZV1kphEEXn8', start_time: 0, end_time: 90,
    tags: t('cinematic','real-estate'),
  },
  {
    id: 'atonement', title: 'Atonement', shotName: 'Epic beach long-take',
    category: 'Smooth Tracking & Steadicam',
    description: 'Sustained tracking across a vast beach tableau.',
    motion_behavior: t('long tracking','crowd parallax','observational'),
    emotional_tone: t('elegiac','overwhelming','melancholy'),
    cinematic_keywords: t('long take','beach tableau','melancholy'),
    prompt_injection: 'epic sustained tracking shot across a vast tableau with crowd parallax, elegiac melancholy pacing, golden-grey color palette, observational long-take grandeur',
    youtube_id: '55CaD_j5FQs', start_time: 0, end_time: 60,
    tags: t('cinematic'),
  },
  {
    id: 'boogie-nights', title: 'Boogie Nights', shotName: 'Party-entry long tracking',
    category: 'Smooth Tracking & Steadicam',
    description: 'High-energy Steadicam entry — outside to inside in one breath.',
    motion_behavior: t('exterior-to-interior','character pick-ups','party energy'),
    emotional_tone: t('euphoric','glossy','propulsive'),
    cinematic_keywords: t('steadicam party entry','character hand-off','disco glow'),
    prompt_injection: 'euphoric steadicam party-entry tracking shot moving from exterior to interior, character hand-offs through the frame, glossy disco glow, propulsive musical pacing',
    youtube_id: 'iiXtFyZqvQQ', start_time: 0, end_time: 90,
    tags: t('music-video','cinematic'),
  },
  {
    id: 'touch-of-evil', title: 'Touch of Evil', shotName: 'Crane-track opening suspense',
    category: 'Smooth Tracking & Steadicam',
    description: 'Choreographed crane + track combining streets, crowds, and ticking dread.',
    motion_behavior: t('crane','track','choreographed citywide'),
    emotional_tone: t('suspense','noir','dread'),
    cinematic_keywords: t('crane and track','noir','ticking-clock'),
    prompt_injection: 'choreographed crane-and-tracking shot across a busy noir street, ticking-clock suspense, deep shadows and neon, weaving through crowds',
    youtube_id: 'EhmYY5ZMXOY', start_time: 0, end_time: 200,
    tags: t('cinematic'),
  },
  {
    id: 'sunrise', title: 'Sunrise', shotName: 'Early-cinema floating movement',
    category: 'Smooth Tracking & Steadicam',
    description: 'Silent-era floating camera that drifts through the dream.',
    motion_behavior: t('drifting float','dreamy lateral','silent-era'),
    emotional_tone: t('dreamlike','romantic','timeless'),
    cinematic_keywords: t('floating drift','silent-era','poetic'),
    prompt_injection: 'silent-era floating camera drifting laterally through a dreamlike landscape, poetic romantic pacing, monochrome silver tone, weightless glide',
    youtube_id: '6NayFytQeBE', start_time: 0, end_time: 60,
    tags: t('cinematic'),
  },
  {
    id: 'conformist', title: 'The Conformist', shotName: 'Stylish gliding symmetry',
    category: 'Smooth Tracking & Steadicam',
    description: 'Architectural symmetry with elegant lateral tracking.',
    motion_behavior: t('lateral track','architectural symmetry','elegant glide'),
    emotional_tone: t('sophisticated','cool','sinister'),
    cinematic_keywords: t('architectural symmetry','art deco','elegant track'),
    prompt_injection: 'stylish gliding lateral tracking shot across architectural symmetry, art-deco color blocking, sinister sophisticated cool, painterly composition',
    youtube_id: 'AzHyXhTlT90', start_time: 0, end_time: 60,
    tags: t('cinematic','real-estate'),
  },
  {
    id: 'i-am-cuba', title: 'I Am Cuba', shotName: 'Impossible floating transitions',
    category: 'Smooth Tracking & Steadicam',
    description: 'Camera glides off rooftops into pools — gravity-defying long takes.',
    motion_behavior: t('rooftop-to-pool','impossible transitions','floating'),
    emotional_tone: t('virtuosic','dreamlike','astonishing'),
    cinematic_keywords: t('impossible long take','rooftop dive','floating transitions'),
    prompt_injection: 'gravity-defying long-take camera drifting through impossible transitions — rooftops, balconies, into water — virtuosic floating motion, dreamlike monochrome',
    youtube_id: 'h1Kw2IfxsQ4', start_time: 0, end_time: 120,
    tags: t('cinematic','viral'),
  },

  // ───────── SIGNATURE EFFECTS ─────────
  {
    id: 'matrix', title: 'The Matrix', shotName: 'Bullet time / frozen rotational',
    category: 'Signature Effects',
    description: 'Time frozen while the camera orbits the subject.',
    motion_behavior: t('time freeze','360 orbit','speed ramp'),
    emotional_tone: t('iconic','powerful','futuristic'),
    cinematic_keywords: t('bullet time','frozen orbit','speed ramp'),
    prompt_injection: 'bullet-time frozen rotational orbit around the subject, full 360 sweep with time nearly stopped, speed-ramp into normal motion, green-tinted future palette, raindrops suspended in air',
    youtube_id: '8DajVKAkL50', start_time: 0, end_time: 15,
    tags: t('viral','action','music-video'),
  },
  {
    id: 'vertigo', title: 'Vertigo', shotName: 'Dolly zoom psychological distortion',
    category: 'Signature Effects',
    description: 'Subject stays still while background warps — classic vertigo effect.',
    motion_behavior: t('dolly-in zoom-out','background warp','subject locked'),
    emotional_tone: t('dread','disorientation','obsession'),
    cinematic_keywords: t('dolly zoom','vertigo effect','background warp'),
    prompt_injection: 'classic dolly-zoom (vertigo effect) — camera dollies in while zooming out, subject framed identical, background visibly warps and compresses, psychological dread',
    youtube_id: 'G7YJkBcRWB8', start_time: 0, end_time: 8,
    tags: t('cinematic','viral'),
  },
  {
    id: 'jaws', title: 'Jaws', shotName: 'Panic dolly zoom',
    category: 'Signature Effects',
    description: 'Sudden realization dolly zoom on a seated subject.',
    motion_behavior: t('sudden dolly zoom','seated subject','realization'),
    emotional_tone: t('shock','realization','panic'),
    cinematic_keywords: t('dolly zoom','beach realization','horror'),
    prompt_injection: 'sudden panic dolly-zoom on a seated subject, background compresses violently, beach realization horror beat, fast onset within one second',
    youtube_id: 'U1fu_sA7XhE', start_time: 0, end_time: 6,
    tags: t('horror','viral'),
  },
  {
    id: 'inception', title: 'Inception', shotName: 'Rotating hallway',
    category: 'Signature Effects',
    description: 'Practical rotating-room camera locked to a tumbling subject.',
    motion_behavior: t('continuous rotation','locked-to-subject','gravity inversion'),
    emotional_tone: t('surreal','tense','wondrous'),
    cinematic_keywords: t('rotating hallway','practical effect','gravity flip'),
    prompt_injection: 'practical rotating-hallway camera locked to the tumbling subject, continuous 360 gravity inversion, surreal tense action, polished steely color',
    youtube_id: 'X-KDt-G1pJ0', start_time: 0, end_time: 25,
    tags: t('action','viral','cinematic'),
  },
  {
    id: 'humble', title: 'Kendrick Lamar — HUMBLE.', shotName: 'Robotic arm precision',
    category: 'Signature Effects',
    description: 'Programmed robotic-arm camera with snap precision and tableau cuts.',
    motion_behavior: t('robotic arm','snap precision','tableau drops'),
    emotional_tone: t('iconic','confident','sacred'),
    cinematic_keywords: t('motion control','robotic arm','tableau'),
    prompt_injection: 'motion-control robotic-arm cinematography with snap precision moves, perfectly composed tableau drops, sacred iconography framing, high-contrast color, music-video confidence',
    youtube_id: 'tvTRZJ-4EyI', start_time: 60, end_time: 90,
    tags: t('music-video','viral','cinematic'),
  },
  {
    id: 'freak-on-a-leash', title: 'Korn — Freak on a Leash', shotName: 'Early bullet-time',
    category: 'Signature Effects',
    description: 'Bullet skips through space while time stretches — early VFX bullet time.',
    motion_behavior: t('time stretch','through-the-scene','POV bullet'),
    emotional_tone: t('chaotic','playful','aggressive'),
    cinematic_keywords: t('early bullet time','POV bullet','time stretch'),
    prompt_injection: 'early bullet-time POV traveling through a stretched-time scene, aggressive nu-metal energy, kinetic time-fragment cuts',
    youtube_id: 'jRGrNDV2mKc', start_time: 60, end_time: 90,
    tags: t('music-video','viral'),
  },
  {
    id: 'movie-camera', title: 'Man with a Movie Camera', shotName: 'Experimental motion tricks',
    category: 'Signature Effects',
    description: 'Dutch tilts, split screen, time tricks — early experimental city symphony.',
    motion_behavior: t('split screen','time tricks','dutch tilts'),
    emotional_tone: t('experimental','playful','rhythmic'),
    cinematic_keywords: t('city symphony','split screen','experimental cuts'),
    prompt_injection: 'experimental city-symphony cinematography, split screen overlays, dutch tilts, rhythmic time tricks, monochrome silver tone',
    youtube_id: '3GyNB4-eN1E', start_time: 0, end_time: 60,
    tags: t('cinematic','viral'),
  },
  {
    id: 'barry-lyndon', title: 'Barry Lyndon', shotName: 'Candlelit NASA-lens look',
    category: 'Signature Effects',
    description: 'Shot at f/0.7 on NASA Zeiss glass — painterly candlelight.',
    motion_behavior: t('static','slow zoom-out','painterly'),
    emotional_tone: t('regal','painterly','still'),
    cinematic_keywords: t('candlelight','f/0.7','painterly tableau'),
    prompt_injection: 'painterly candlelit cinematography on ultra-fast lenses, very shallow depth of field, slow majestic zoom-out reveal, oil-painting tableau composition',
    youtube_id: 'YQE73GDo4So', start_time: 0, end_time: 30,
    tags: t('cinematic','real-estate'),
  },
  {
    id: 'tree-of-life', title: 'The Tree of Life', shotName: 'Cosmic floating grace',
    category: 'Signature Effects',
    description: 'Floating low-wide camera drifting through golden grace.',
    motion_behavior: t('low-wide drift','sun-flare','floating'),
    emotional_tone: t('spiritual','tender','wondrous'),
    cinematic_keywords: t('low-wide','sun flare','floating drift'),
    prompt_injection: 'low-wide floating cinematography with constant sun-flare, drifting graceful motion, golden hour wonder, spiritual painterly color',
    youtube_id: 'RrAz1YLh8nY', start_time: 0, end_time: 60,
    tags: t('cinematic','real-estate'),
  },
  {
    id: '2001', title: '2001: A Space Odyssey', shotName: 'Mathematically precise space movement',
    category: 'Signature Effects',
    description: 'Locked symmetrical compositions with majestic slow drift.',
    motion_behavior: t('locked symmetry','slow drift','one-point perspective'),
    emotional_tone: t('majestic','still','sublime'),
    cinematic_keywords: t('symmetry','one-point perspective','slow drift'),
    prompt_injection: 'mathematically precise symmetrical cinematography, majestic slow drift, one-point perspective, sublime stillness, classical orchestral pacing',
    youtube_id: 'oR_e9y-bka0', start_time: 0, end_time: 60,
    tags: t('cinematic'),
  },

  // ───────── CREATIVE ANGLES & FRAMING ─────────
  {
    id: 'third-man', title: 'The Third Man', shotName: 'Dutch-angle tension',
    category: 'Creative Angles & Framing',
    description: 'Tilted horizons that signal moral imbalance.',
    motion_behavior: t('tilt frame','static','shadow play'),
    emotional_tone: t('paranoid','noir','off-balance'),
    cinematic_keywords: t('dutch angle','noir shadows','tilt'),
    prompt_injection: 'dutch-angle noir cinematography with tilted horizons, dramatic shadow play, paranoid off-balance composition, high-contrast monochrome',
    youtube_id: 'r9yyDEDGlr0', start_time: 0, end_time: 30,
    tags: t('cinematic'),
  },
  {
    id: 'citizen-kane', title: 'Citizen Kane', shotName: 'Deep-focus low-angle power',
    category: 'Creative Angles & Framing',
    description: 'Ceilings in frame, low angles, everything in deep focus.',
    motion_behavior: t('static','low-angle','deep focus'),
    emotional_tone: t('powerful','monumental','isolated'),
    cinematic_keywords: t('deep focus','low angle','ceilings'),
    prompt_injection: 'deep-focus low-angle cinematography with ceilings in frame, everything sharp from foreground to background, monumental power composition, monochrome',
    youtube_id: '8dxh3lwdOFw', start_time: 0, end_time: 30,
    tags: t('cinematic','real-estate'),
  },
  {
    id: 'suspiria', title: 'Suspiria (1977)', shotName: 'Expressionist color framing',
    category: 'Creative Angles & Framing',
    description: 'Saturated gel lighting — red, blue, green — and unnatural geometry.',
    motion_behavior: t('static stylized','color gel','geometric framing'),
    emotional_tone: t('hallucinatory','dread','vivid'),
    cinematic_keywords: t('color gels','expressionist','geometric'),
    prompt_injection: 'expressionist horror cinematography with saturated red and blue color gels, geometric framing, hallucinatory production design, baroque dread',
    youtube_id: 'hPs2ExUL_bc', start_time: 0, end_time: 30,
    tags: t('horror','cinematic'),
  },
  {
    id: 'lighthouse', title: 'The Lighthouse', shotName: 'Boxed aspect-ratio isolation',
    category: 'Creative Angles & Framing',
    description: '1.19:1 boxed frame with high-contrast monochrome.',
    motion_behavior: t('locked frame','static','wide lens distortion'),
    emotional_tone: t('claustrophobic','feral','mythic'),
    cinematic_keywords: t('1.19:1','monochrome','isolation'),
    prompt_injection: 'boxed 1.19:1 aspect ratio cinematography, high-contrast silver monochrome, wide-lens claustrophobic isolation, mythic feral mood',
    youtube_id: 'Hyag7lR8CPA', start_time: 0, end_time: 30,
    tags: t('horror','cinematic'),
  },
  {
    id: 'in-the-mood', title: 'In the Mood for Love', shotName: 'Framing within framing',
    category: 'Creative Angles & Framing',
    description: 'Doorways, mirrors, and lattices frame the subject inside the frame.',
    motion_behavior: t('static','slow push','frame-in-frame'),
    emotional_tone: t('yearning','intimate','melancholy'),
    cinematic_keywords: t('frame-in-frame','doorways','golden lattice'),
    prompt_injection: 'frame-within-frame cinematography through doorways and lattices, slow yearning push, golden-jade color palette, intimate melancholy',
    youtube_id: 'm8GuedsQnWQ', start_time: 0, end_time: 30,
    tags: t('cinematic','real-estate','music-video'),
  },
  {
    id: 'hero', title: 'Hero (2002)', shotName: 'Color-coded wuxia elegance',
    category: 'Creative Angles & Framing',
    description: 'Each chapter a single dominant color — choreographed sweeping camera.',
    motion_behavior: t('sweeping pan','choreographed','color block'),
    emotional_tone: t('mythic','operatic','elegant'),
    cinematic_keywords: t('monochrome color block','sweeping pan','wuxia'),
    prompt_injection: 'wuxia cinematography with a single dominant color flooding the frame, sweeping choreographed pans, operatic elegant motion',
    youtube_id: '_USDk5jaGek', start_time: 0, end_time: 60,
    tags: t('cinematic','music-video'),
  },
  {
    id: 'pans-labyrinth', title: "Pan's Labyrinth", shotName: 'Fantasy realism lighting',
    category: 'Creative Angles & Framing',
    description: 'Cold steel reality vs warm amber fantasy — split palette per world.',
    motion_behavior: t('steady drift','dual palette','tableau'),
    emotional_tone: t('mournful','magical','dark'),
    cinematic_keywords: t('dual palette','amber/steel','fantasy realism'),
    prompt_injection: 'fantasy-realism cinematography splitting cold steel reality from warm amber fantasy, steady drifting camera, mournful magical atmosphere',
    youtube_id: 'jVZRnnVSQ8k', start_time: 0, end_time: 30,
    tags: t('cinematic','horror'),
  },
  {
    id: 'roma', title: 'Roma', shotName: 'Cinematic long digital pans',
    category: 'Creative Angles & Framing',
    description: 'Slow 180-degree digital pans across detailed black-and-white tableaus.',
    motion_behavior: t('slow long pan','tableau','digital monochrome'),
    emotional_tone: t('contemplative','observational','warm'),
    cinematic_keywords: t('long slow pan','black and white','tableau'),
    prompt_injection: 'slow 180-degree digital pan across a richly detailed monochrome tableau, contemplative observational pacing, deep depth-of-field',
    youtube_id: '6BS27ngZtxg', start_time: 0, end_time: 60,
    tags: t('cinematic','real-estate'),
  },
  {
    id: 'the-fall', title: 'The Fall', shotName: 'Dreamlike surreal compositions',
    category: 'Creative Angles & Framing',
    description: 'Globe-spanning practical locations framed like storybook paintings.',
    motion_behavior: t('symmetrical tableau','wide static','practical scale'),
    emotional_tone: t('whimsical','epic','painterly'),
    cinematic_keywords: t('storybook tableau','practical locations','symmetrical'),
    prompt_injection: 'dreamlike storybook cinematography, symmetrical tableau composition, epic practical locations, painterly saturated color',
    youtube_id: 'OTn5XUFP_iA', start_time: 0, end_time: 30,
    tags: t('cinematic'),
  },
  {
    id: 'evil-dead', title: 'Evil Dead', shotName: 'Demon-POV rushing movement',
    category: 'Creative Angles & Framing',
    description: 'Low-mount rig flying through forest from the demon\'s POV.',
    motion_behavior: t('low-mount POV','forest sprint','impossible trajectory'),
    emotional_tone: t('feral','hunting','terror'),
    cinematic_keywords: t('demon POV','low-mount','forest rush'),
    prompt_injection: 'low-mounted demon-POV rushing through forest, impossible flying trajectory, feral hunting energy, branches blurring past the lens',
    youtube_id: 'TnQiog7v4sQ', start_time: 0, end_time: 20,
    tags: t('horror','viral'),
  },

  // ───────── VIRAL / EXPERIMENTAL / TIME ─────────
  {
    id: 'black-beatles', title: 'Rae Sremmurd — Black Beatles (Mannequin Challenge)', shotName: 'Freeze-time mannequin',
    category: 'Viral / Experimental / Time',
    description: 'Camera floats through a fully frozen tableau.',
    motion_behavior: t('continuous float','frozen subjects','room-to-room'),
    emotional_tone: t('uncanny','playful','iconic'),
    cinematic_keywords: t('frozen tableau','mannequin challenge','float-through'),
    prompt_injection: 'floating camera moving through a fully frozen mannequin-challenge tableau, every subject perfectly still, uncanny playful energy',
    youtube_id: 'b8m9zhNAgKs', start_time: 0, end_time: 60,
    tags: t('viral','music-video'),
  },
  {
    id: 'oldboy', title: 'Oldboy', shotName: 'Side-scroll hallway one-take',
    category: 'Viral / Experimental / Time',
    description: 'Lateral one-take fight in a corridor — pure side-scroll game energy.',
    motion_behavior: t('lateral track','one-take fight','side-scroll'),
    emotional_tone: t('brutal','exhausted','iconic'),
    cinematic_keywords: t('side-scroll','corridor fight','one-take'),
    prompt_injection: 'lateral side-scroll one-take corridor fight cinematography, perfect 90-degree profile framing, brutal exhausted realism, no cuts',
    youtube_id: 'gvQ7Z6ZCxTc', start_time: 0, end_time: 60,
    tags: t('action','viral','cinematic'),
  },
  {
    id: 'gravity', title: 'Gravity', shotName: 'Zero-gravity floating',
    category: 'Viral / Experimental / Time',
    description: 'CG-augmented continuous orbital float around the subject.',
    motion_behavior: t('orbital float','tumble','seamless POV swap'),
    emotional_tone: t('isolating','vertiginous','awe'),
    cinematic_keywords: t('orbital float','zero-G','seamless POV'),
    prompt_injection: 'continuous orbital floating camera around a subject in zero gravity, seamless POV swaps, vertiginous awe, hard sunlight against pitch black',
    youtube_id: 'OiTiKOy59o4', start_time: 0, end_time: 60,
    tags: t('cinematic','viral'),
  },
  {
    id: 'dunkirk', title: 'Dunkirk', shotName: 'IMAX urgency perspective',
    category: 'Viral / Experimental / Time',
    description: 'IMAX wide POVs that put you in the cockpit, on the beach, underwater.',
    motion_behavior: t('immersive POV','wide IMAX','first-person'),
    emotional_tone: t('urgent','overwhelming','heroic'),
    cinematic_keywords: t('IMAX','first-person','ticking clock'),
    prompt_injection: 'IMAX immersive first-person POV cinematography, ticking-clock urgency, ultra-wide framing, overwhelming scale, naturalistic light',
    youtube_id: 'F-eMt3SrfFU', start_time: 0, end_time: 60,
    tags: t('action','cinematic'),
  },
  {
    id: 'lala-land', title: 'La La Land', shotName: 'Musical whip pans',
    category: 'Viral / Experimental / Time',
    description: 'Sweeping whip pans choreographed to a single take of song and dance.',
    motion_behavior: t('whip pan','choreographed long take','musical'),
    emotional_tone: t('joyful','romantic','nostalgic'),
    cinematic_keywords: t('whip pan','musical one-take','technicolor'),
    prompt_injection: 'choreographed musical one-take cinematography with sweeping whip pans, joyful romantic energy, technicolor highway palette',
    youtube_id: '7CVfTd-_qbc', start_time: 0, end_time: 90,
    tags: t('music-video','cinematic','viral'),
  },
  {
    id: 'grand-budapest', title: 'The Grand Budapest Hotel', shotName: 'Symmetrical precision framing',
    category: 'Viral / Experimental / Time',
    description: 'Locked symmetrical centered composition with snap whip pans.',
    motion_behavior: t('snap whip pan','centered symmetry','tableau'),
    emotional_tone: t('whimsical','elegant','precise'),
    cinematic_keywords: t('symmetry','snap pan','pastel'),
    prompt_injection: 'centered symmetrical Wes-Anderson-style cinematography, snap whip pans, pastel tableau composition, whimsical precise blocking',
    youtube_id: '1Fg5iWmQjwk', start_time: 0, end_time: 30,
    tags: t('cinematic','viral','real-estate'),
  },
  {
    id: 'stalker', title: 'Stalker', shotName: 'Hypnotic slow movement',
    category: 'Viral / Experimental / Time',
    description: 'Extremely slow tracking through textures and atmosphere.',
    motion_behavior: t('extremely slow track','texture drift','meditative'),
    emotional_tone: t('meditative','foreboding','transcendent'),
    cinematic_keywords: t('slow tracking','atmospheric drift','textural'),
    prompt_injection: 'extremely slow hypnotic tracking shot across textured atmospheric terrain, meditative foreboding pacing, sepia-green color',
    youtube_id: 'inAWT9kScbg', start_time: 0, end_time: 90,
    tags: t('cinematic'),
  },
  {
    id: 'seven-samurai', title: 'Seven Samurai', shotName: 'Rain-soaked multi-camera chaos',
    category: 'Viral / Experimental / Time',
    description: 'Multiple long lenses capture muddy rain-soaked battle from layered distances.',
    motion_behavior: t('telephoto compression','multi-camera','rain action'),
    emotional_tone: t('exhausted','heroic','mud-and-rain'),
    cinematic_keywords: t('telephoto','rain battle','multi-camera'),
    prompt_injection: 'telephoto multi-camera cinematography of a rain-soaked battle, layered compression, exhausted heroic mud-and-rain realism, deep monochrome',
    youtube_id: 'GOgeAf1L2Ik', start_time: 0, end_time: 60,
    tags: t('action','cinematic'),
  },
  {
    id: 'joan-of-arc', title: 'The Passion of Joan of Arc', shotName: 'Emotional extreme close-up',
    category: 'Viral / Experimental / Time',
    description: 'Unflinching close-ups against blank backgrounds — pure face.',
    motion_behavior: t('static close-up','blank background','intimate'),
    emotional_tone: t('spiritual','anguished','transcendent'),
    cinematic_keywords: t('extreme close-up','blank background','face'),
    prompt_injection: 'unflinching extreme close-up cinematography against a blank monochrome background, intimate spiritual anguish, every pore visible',
    youtube_id: '1mbsGj2WS1s', start_time: 0, end_time: 30,
    tags: t('cinematic'),
  },
  {
    id: 'moonlight', title: 'Moonlight', shotName: 'Emotional color-palette intimacy',
    category: 'Viral / Experimental / Time',
    description: 'Saturated teal-magenta skin tones, intimate handheld emotion.',
    motion_behavior: t('intimate handheld','character orbit','soft'),
    emotional_tone: t('tender','longing','vulnerable'),
    cinematic_keywords: t('teal magenta','intimate handheld','character orbit'),
    prompt_injection: 'intimate handheld cinematography with saturated teal-magenta skin tones, tender longing emotion, soft character orbit, naturalistic Miami light',
    youtube_id: '9NJj12tJzqc', start_time: 0, end_time: 60,
    tags: t('cinematic','music-video'),
  },
];

// ───────── Smart recommendation hints ─────────
const RECOMMEND_MAP: { match: RegExp; ids: string[] }[] = [
  { match: /luxury|mansion|estate|villa|penthouse/i, ids: ['goodfellas','roma','barry-lyndon','humble','tree-of-life','grand-budapest'] },
  { match: /horror|haunt|scary|creep|dark|monster|demon/i, ids: ['cloverfield','evil-dead','blair-witch','28-days-later','shining','suspiria','lighthouse'] },
  { match: /chase|fight|action|combat|war|battle/i, ids: ['cloverfield','mad-max','saving-private-ryan','oldboy','inception','dunkirk'] },
  { match: /music|rap|hip[\s-]?hop|song|concert|video clip/i, ids: ['humble','black-beatles','lala-land','moonlight','freak-on-a-leash','matrix'] },
  { match: /real estate|home|house|property|listing|kitchen|bedroom/i, ids: ['goodfellas','grand-budapest','citizen-kane','roma','in-the-mood','tree-of-life'] },
  { match: /doc|interview|news|reportage/i, ids: ['big-short','city-of-god','children-of-men'] },
  { match: /space|cosmic|sci-?fi|alien|future/i, ids: ['2001','gravity','matrix','inception'] },
  { match: /dream|surreal|fantasy/i, ids: ['the-fall','tree-of-life','pans-labyrinth','i-am-cuba'] },
  { match: /walk|tour|fashion|runway|hallway/i, ids: ['birdman','goodfellas','oldboy','shining','grand-budapest'] },
];

export function recommendStyles(promptText: string): DirectorStyle[] {
  const hits = new Set<string>();
  for (const { match, ids } of RECOMMEND_MAP) {
    if (match.test(promptText)) ids.forEach(id => hits.add(id));
  }
  return DIRECTOR_STYLES.filter(s => hits.has(s.id));
}

export function buildInjectedPrompt(basePrompt: string, styles: DirectorStyle[]): string {
  const base = basePrompt.trim();
  if (styles.length === 0) return base;
  const injections = styles.map(s => s.prompt_injection).join('; ');
  const cameras = Array.from(new Set(styles.map(s => s.shotName))).join(' blended with ');
  const tone = Array.from(new Set(styles.flatMap(s => s.emotional_tone))).slice(0, 6).join(', ');
  const tail = `Cinematography style: ${cameras}. Mood: ${tone}. Direction: ${injections}.`;
  return base ? `${base} ${tail}` : tail;
}

export function getThumbnail(s: DirectorStyle): string {
  if (s.thumbnail) return s.thumbnail;
  if (s.youtube_id) return `https://img.youtube.com/vi/${s.youtube_id}/hqdefault.jpg`;
  return '';
}

export const DIRECTOR_FILTER_TAGS: { key: string; label: string }[] = [
  { key: 'viral',        label: 'Most Viral' },
  { key: 'cinematic',    label: 'Most Cinematic' },
  { key: 'action',       label: 'Best for Action' },
  { key: 'horror',       label: 'Best for Horror' },
  { key: 'music-video',  label: 'Best for Music Videos' },
  { key: 'real-estate',  label: 'Best for Luxury Real Estate' },
  { key: 'documentary',  label: 'Best for Documentary' },
];

export const DIRECTOR_CATEGORIES: DirectorCategory[] = [
  'Handheld & Chaotic',
  'Smooth Tracking & Steadicam',
  'Signature Effects',
  'Creative Angles & Framing',
  'Viral / Experimental / Time',
];
