UPDATE site_configs 
SET content = jsonb_set(
  content,
  '{invoicing}',
  to_jsonb('INVOICE PDF EMAIL SYSTEM — PROFESSIONAL ATTACHMENT WORKFLOW

All invoice email delivery through API paths now sends a professionally designed PDF attachment generated by invoice-api before dispatching through Gmail.

Creating + Auto-Sending Invoice:
POST /invoice-api
Body: { customer_email: "x@y.com", line_items: [...], auto_send: true }
Result: Creates invoice, generates professional PDF, attaches PDF, sends via Gmail.

Sending Existing Invoice:
POST /invoice-api?action=send-invoice
Body: { invoice_id: "uuid" }
Result: Generates professional PDF for existing invoice and emails as attachment.

Via CRM Proxy:
POST /clawd-bot/send-invoice
Body: { invoice_id: "uuid" }
Result: Proxies to invoice-api send-invoice with the same PDF attachment behavior.

PAID IN FULL LOGIC:
When an invoice has status = "paid", the system automatically:
1. Adds a green "PAID IN FULL" banner to the email header
2. Changes email subject to: "Invoice [INV-XXXXX] — PAID IN FULL — Receipt from STU25"
3. Email body says "receipt" instead of "invoice" — confirms no further action needed
4. PDF gets a large green "PAID IN FULL" stamp with the payment date
5. Invoice status is NOT overwritten back to "sent" — it stays "paid"
6. The sent_at timestamp is still updated for record-keeping

When user says "send invoice" for a paid invoice, Cortex should confirm:
✅ Invoice [INV-XXXXX] receipt sent to [email] with PAID IN FULL PDF — $[amount]

Rules:
1. ALWAYS use auto_send: true for immediate invoice delivery.
2. ALWAYS rely on invoice-api to generate the invoice PDF attachment.
3. NEVER construct manual/plain invoice bodies for delivery through /clawd-bot/email.
4. For unpaid invoices, confirm: ✅ Invoice [INV-XXXXX] sent to [email] with PDF attachment — $[amount].
5. For paid invoices, confirm: ✅ Invoice [INV-XXXXX] PAID IN FULL receipt sent to [email] — $[amount].
6. This PDF workflow is the required default for all API-driven invoice sending.
7. The invoice-api handles all paid/unpaid detection automatically — no extra flags needed.'::text)
)
WHERE site_id = 'cortex' AND section = 'soul'