
-- Insert original week (week 0) for Lamb: March 17-23
INSERT INTO calendar_events (title, description, start_time, end_time, source, source_id, category, color)
VALUES
('♻️ [INSTAGRAM] 🎵 Fresh sounds from @lamb.wavv! Start your week right 🔥', 
 E'Original Week — Lamb Music\nProfile: NysonBlack\nType: video\nMedia URL: https://mziuxsfxevjnmdwnrqjs.supabase.co/storage/v1/object/public/content-uploads/ai-generated/NysonBlack/cortex-strategist/1773728419027_overkill_7.mp4\n\n🎵 Fresh sounds from @lamb.wavv! Start your week right 🔥\n#Lambwavv #NewMusic #MusicDiscovery',
 '2026-03-17T18:00:00', '2026-03-17T18:30:00', 'smm', 'original-w0-lamb-day1', 'smm', '#E1306C'),
('♻️ [INSTAGRAM] 🎵 @lamb.wavv bringing the heat today! Share with someone 🔥',
 E'Original Week — Lamb Music\nProfile: NysonBlack\nType: video\nMedia URL: https://mziuxsfxevjnmdwnrqjs.supabase.co/storage/v1/object/public/content-uploads/ai-generated/NysonBlack/cortex-strategist/1773728423681_Overkill_6.mp4\n\n🎵 @lamb.wavv bringing the heat today! Share with someone 🔥\n#Lambwavv #MusicVibes #ShareGoodMusic',
 '2026-03-18T18:00:00', '2026-03-18T18:30:00', 'smm', 'original-w0-lamb-day2', 'smm', '#E1306C'),
('♻️ [INSTAGRAM] 🎵 Can''t stop replaying @lamb.wavv! Tag a friend 🎶',
 E'Original Week — Lamb Music\nProfile: NysonBlack\nType: video\nMedia URL: https://mziuxsfxevjnmdwnrqjs.supabase.co/storage/v1/object/public/content-uploads/ai-generated/NysonBlack/cortex-strategist/1773728429703_overkill_5.mp4\n\n🎵 Can''t stop replaying @lamb.wavv! Tag a friend 🎶\n#Lambwavv #MusicLover #InstaMusic',
 '2026-03-19T18:00:00', '2026-03-19T18:30:00', 'smm', 'original-w0-lamb-day3', 'smm', '#E1306C'),
('♻️ [INSTAGRAM] 🎵 Midweek vibes with @lamb.wavv! What''s your mood? 🌊',
 E'Original Week — Lamb Music\nProfile: NysonBlack\nType: video\nMedia URL: https://mziuxsfxevjnmdwnrqjs.supabase.co/storage/v1/object/public/content-uploads/ai-generated/NysonBlack/cortex-strategist/1773728435164_overkill_4.mp4\n\n🎵 Midweek vibes with @lamb.wavv! What''s your mood? 🌊\n#Lambwavv #WeekendVibes #GoodVibes',
 '2026-03-20T18:00:00', '2026-03-20T18:30:00', 'smm', 'original-w0-lamb-day4', 'smm', '#E1306C'),
('♻️ [INSTAGRAM] 🎵 @lamb.wavv on repeat all day! Share the vibe 🎧',
 E'Original Week — Lamb Music\nProfile: NysonBlack\nType: video\nMedia URL: https://mziuxsfxevjnmdwnrqjs.supabase.co/storage/v1/object/public/content-uploads/ai-generated/NysonBlack/cortex-strategist/1773728440147_overkill_3.mp4\n\n🎵 @lamb.wavv on repeat all day! Share the vibe 🎧\n#Lambwavv #PlaylistGoals #MusicDiscovery',
 '2026-03-21T18:00:00', '2026-03-21T18:30:00', 'smm', 'original-w0-lamb-day5', 'smm', '#E1306C'),
('♻️ [INSTAGRAM] 🎵 Weekend energy with @lamb.wavv! Send to your crew 💪',
 E'Original Week — Lamb Music\nProfile: NysonBlack\nType: video\nMedia URL: https://mziuxsfxevjnmdwnrqjs.supabase.co/storage/v1/object/public/content-uploads/ai-generated/NysonBlack/cortex-strategist/1773728444596_overkill_2.mp4\n\n🎵 Weekend energy with @lamb.wavv! Send to your crew 💪\n#Lambwavv #GoodVibes #MusicShare',
 '2026-03-22T18:00:00', '2026-03-22T18:30:00', 'smm', 'original-w0-lamb-day6', 'smm', '#E1306C'),
('♻️ [INSTAGRAM] 🎵 Closing the week strong with @lamb.wavv! Share the love ❤️',
 E'Original Week — Lamb Music\nProfile: NysonBlack\nType: video\nMedia URL: https://mziuxsfxevjnmdwnrqjs.supabase.co/storage/v1/object/public/content-uploads/ai-generated/NysonBlack/cortex-strategist/1773728449625_OvERKill_01.mp4\n\n🎵 Closing the week strong with @lamb.wavv! Share the love ❤️\n#Lambwavv #MusicWeek #ShareTheMusic',
 '2026-03-23T18:00:00', '2026-03-23T18:30:00', 'smm', 'original-w0-lamb-day7', 'smm', '#E1306C'),

-- Insert original week (week 0) for Oranj: March 17-23
('♻️ [INSTAGRAM] 🔥 @oranjgoodman bringing the heat! Who are you sharing this with? 🎶',
 E'Original Week — OranJ Goodman Music\nProfile: NysonBlack\nType: video\nMedia URL: https://mziuxsfxevjnmdwnrqjs.supabase.co/storage/v1/object/public/content-uploads/ai-generated/NysonBlack/cortex-strategist/1773734059761_OJ_6.mp4\n\n🔥 @oranjgoodman bringing the heat! #OranJGoodman #NewMusic\n\n🎤 @oranjgoodman',
 '2026-03-17T22:00:00', '2026-03-17T22:30:00', 'smm', 'original-w0-ojg-day1', 'smm', '#E1306C'),
('♻️ [INSTAGRAM] 🔥 Vibes on point with @oranjgoodman! Tag a friend 👇',
 E'Original Week — OranJ Goodman Music\nProfile: NysonBlack\nType: video\nMedia URL: https://mziuxsfxevjnmdwnrqjs.supabase.co/storage/v1/object/public/content-uploads/ai-generated/NysonBlack/cortex-strategist/1773734067211_OJ_5.mp4\n\n🔥 Vibes with @oranjgoodman! #OranJGoodman #MusicVibes\n\n🎤 @oranjgoodman',
 '2026-03-18T22:00:00', '2026-03-18T22:30:00', 'smm', 'original-w0-ojg-day2', 'smm', '#E1306C'),
('♻️ [INSTAGRAM] 🔥 Get lost in the rhythm with @oranjgoodman 🎵',
 E'Original Week — OranJ Goodman Music\nProfile: NysonBlack\nType: video\nMedia URL: https://mziuxsfxevjnmdwnrqjs.supabase.co/storage/v1/object/public/content-uploads/ai-generated/NysonBlack/cortex-strategist/1773734074409_Oj_4.mp4\n\n🔥 Lost in the rhythm with @oranjgoodman! #OranJGoodman #WeekendVibes\n\n🎤 @oranjgoodman',
 '2026-03-19T22:00:00', '2026-03-19T22:30:00', 'smm', 'original-w0-ojg-day3', 'smm', '#E1306C'),
('♻️ [INSTAGRAM] 🔥 @oranjgoodman dropping pure fire! Can''t get enough 🎶',
 E'Original Week — OranJ Goodman Music\nProfile: NysonBlack\nType: video\nMedia URL: https://mziuxsfxevjnmdwnrqjs.supabase.co/storage/v1/object/public/content-uploads/ai-generated/NysonBlack/cortex-strategist/1773734084606_OJ_3.mp4\n\n🔥 @oranjgoodman dropping fire! #OranJGoodman #FireTrack\n\n🎤 @oranjgoodman',
 '2026-03-20T22:00:00', '2026-03-20T22:30:00', 'smm', 'original-w0-ojg-day4', 'smm', '#E1306C'),
('♻️ [INSTAGRAM] 🔥 This @oranjgoodman track is a mood! Share it 🎧',
 E'Original Week — OranJ Goodman Music\nProfile: NysonBlack\nType: video\nMedia URL: https://mziuxsfxevjnmdwnrqjs.supabase.co/storage/v1/object/public/content-uploads/ai-generated/NysonBlack/cortex-strategist/1773734090740_OJ_2.mp4\n\n🔥 @oranjgoodman is a mood! #OranJGoodman #MoodMusic\n\n🎤 @oranjgoodman',
 '2026-03-21T22:00:00', '2026-03-21T22:30:00', 'smm', 'original-w0-ojg-day5', 'smm', '#E1306C'),
('♻️ [INSTAGRAM] 🔥 @oranjgoodman bringing the energy! Tag who you''d dance with ⚡',
 E'Original Week — OranJ Goodman Music\nProfile: NysonBlack\nType: video\nMedia URL: https://mziuxsfxevjnmdwnrqjs.supabase.co/storage/v1/object/public/content-uploads/ai-generated/NysonBlack/cortex-strategist/1773734099336_OJ_1.mp4\n\n🔥 @oranjgoodman energy! #OranJGoodman #DanceMusic\n\n🎤 @oranjgoodman',
 '2026-03-22T22:00:00', '2026-03-22T22:30:00', 'smm', 'original-w0-ojg-day6', 'smm', '#E1306C'),
('♻️ [INSTAGRAM] 🔥 Ending the week strong with @oranjgoodman! Thoughts? 🎵',
 E'Original Week — OranJ Goodman Music\nProfile: NysonBlack\nType: video\nMedia URL: https://mziuxsfxevjnmdwnrqjs.supabase.co/storage/v1/object/public/content-uploads/ai-generated/NysonBlack/cortex-strategist/1773734108211_OJ_7.mp4\n\n🔥 Week strong with @oranjgoodman! #OranJGoodman #MusicReview\n\n🎤 @oranjgoodman',
 '2026-03-23T22:00:00', '2026-03-23T22:30:00', 'smm', 'original-w0-ojg-day7', 'smm', '#E1306C');
